#!/bin/bash

SOURCE="/home/user/data"
DEST="/home/user/backups"

DATE=$(date +%Y-%m-%d)

BACKUP_NAME="backup-$DATE.tar.gz"

echo "Starting backup..."

tar -czf $DEST/$BACKUP_NAME $SOURCE

echo "Backup saved as $BACKUP_NAME"
