#!/bin/bash

NETWORK="192.168.1"

echo "Scanning network..."

for i in {1..254}
do
  IP="$NETWORK.$i"
  
  ping -c 1 -W 1 $IP > /dev/null
  
  if [ $? -eq 0 ]; then
    echo "[+] Active: $IP"
  fi
done

echo "Scan complete."
