#!/bin/bash

echo "====== System Information ======"

# اسم المستخدم
echo "User: $(whoami)"

# وقت التشغيل
echo "Uptime:"
uptime

# استخدام المعالج
echo "CPU Load:"
top -bn1 | grep "load average"

# استخدام الرام
echo "Memory Usage:"
free -h

# مساحة القرص
echo "Disk Usage:"
df -h

echo "================================"
